server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: test-service
          uri: lb://test
          predicates:
            - Path=/
        - id: file-service
          uri: lb://file
          predicates:
            - Path=/admin/file/**
        - id: goods-category-service
          uri: lb://goodscategory
          predicates:
            - Path=/admin/goods/category/**
        - id: goods-service
          uri: lb://goods
          predicates:
            - Path=/admin/goods/**
        - id: role-service
          uri: lb://role
          predicates:
            - Path=/admin/role/**
        - id: user-service # 路由标示，必须唯一
          uri: lb://user # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/admin/*,/admin/admin/**,/admin/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: menu-service
          uri: lb://menu
          predicates:
            - Path=/admin/menu/**
      #default-filters:
        #- DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
