spring:
  #datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #druid:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #url: jdbc:mysql://localhost:3306/cloud_goods_category?serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true&useSSL=false
    #password: root
    #initialSize: 5
  application:
    name: file
  cloud:
    nacos:
      server-addr: localhost:8848
      #discovery:
        #ephemeral: false # 设置为非临时实例
